// <auto-generated />
using System;
using AppPermisos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppPermisos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120200137_SeedDatosIniciales")]
    partial class SeedDatosIniciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AppPermisos.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("AppPermisos.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "VER_META",
                            Nombre = "Ver módulo Meta"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "VER_INSTAGRAM",
                            Nombre = "Ver módulo Instagram"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "VER_FACEBOOK",
                            Nombre = "Ver módulo Facebook"
                        });
                });

            modelBuilder.Entity("AppPermisos.Models.PermisoUnidadOrganizacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadOrganizacionalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("UnidadOrganizacionalId");

                    b.ToTable("PermisosUnidadesOrganizacionales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermisoId = 1,
                            UnidadOrganizacionalId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermisoId = 2,
                            UnidadOrganizacionalId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermisoId = 3,
                            UnidadOrganizacionalId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermisoId = 2,
                            UnidadOrganizacionalId = 2
                        },
                        new
                        {
                            Id = 5,
                            PermisoId = 3,
                            UnidadOrganizacionalId = 2
                        },
                        new
                        {
                            Id = 6,
                            PermisoId = 2,
                            UnidadOrganizacionalId = 3
                        },
                        new
                        {
                            Id = 7,
                            PermisoId = 3,
                            UnidadOrganizacionalId = 4
                        });
                });

            modelBuilder.Entity("AppPermisos.Models.UnidadOrganizacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnidadPadreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnidadPadreId");

                    b.ToTable("UnidadesOrganizacionales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Marketing",
                            Tipo = "Departamento"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Meta",
                            Tipo = "Subdepartamento",
                            UnidadPadreId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Instagram",
                            Tipo = "Equipo",
                            UnidadPadreId = 2
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Facebook",
                            Tipo = "Equipo",
                            UnidadPadreId = 2
                        });
                });

            modelBuilder.Entity("AppPermisos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDeSangre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadOrganizacionalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnidadOrganizacionalId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppPermisos.Models.Notificacion", b =>
                {
                    b.HasOne("AppPermisos.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppPermisos.Models.PermisoUnidadOrganizacional", b =>
                {
                    b.HasOne("AppPermisos.Models.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppPermisos.Models.UnidadOrganizacional", "UnidadOrganizacional")
                        .WithMany()
                        .HasForeignKey("UnidadOrganizacionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("UnidadOrganizacional");
                });

            modelBuilder.Entity("AppPermisos.Models.UnidadOrganizacional", b =>
                {
                    b.HasOne("AppPermisos.Models.UnidadOrganizacional", "UnidadPadre")
                        .WithMany("Hijos")
                        .HasForeignKey("UnidadPadreId");

                    b.Navigation("UnidadPadre");
                });

            modelBuilder.Entity("AppPermisos.Models.Usuario", b =>
                {
                    b.HasOne("AppPermisos.Models.UnidadOrganizacional", "UnidadOrganizacional")
                        .WithMany()
                        .HasForeignKey("UnidadOrganizacionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadOrganizacional");
                });

            modelBuilder.Entity("AppPermisos.Models.UnidadOrganizacional", b =>
                {
                    b.Navigation("Hijos");
                });
#pragma warning restore 612, 618
        }
    }
}
